### PR TITLE
Modify data processing to handle the case when Day29 markers are not present

### PR DESCRIPTION
**Pull request by youyifong**

### CODE REVIEW

**Comment by youyifong** [comment]
I defined a variable: 
  has29 = "Day29" %in% times 
in the data processing step. Might be useful to move it to _common.R.

**Comment by benkeser** [comment]
> Might be useful to move it to _common.R.

Feel free to modify `_common.R` directly in the PR. And FYI for others working on #196

**Comment by youyifong** [comment]
Done. Shall we merge 197 into 196?

**Comment by benkeser** [comment]
I would suggest merging into #194 and then into master? @nhejazi any preference?

**Comment by youyifong** [comment]
Sounds good to me. Ellis is working on verification as well.

**Comment by benkeser** [comment]
Error message from this build

````
Error in table(Wstratum, TwophasesampInd.2) : 
  object 'TwophasesampInd.2' not found
Calls: %>% -> with -> with.default -> eval -> eval -> table
Execution halted
Makefile:39: recipe for target 'data_processed' failed
make: *** [data_processed] Error 1
````

**Comment by youyifong** [comment]
Sorry. Fix uploaded.

**Comment by nhejazi** [comment]
Merging into #194 sounds good to me

**Pull request closed without merging**
