### PR TITLE
Cor coxph verification

### PR DESCRIPTION
**Pull request by brborate**
Finalized verification code and report for cor_coxph.

### CODE REVIEW

**Comment by thebioengineer** [comment]
hey @brborate - could you include the rendered report as well (pdf)?

**Comment by brborate** [comment]
Thanks Ellis; not sure why it didn't come through. Let me add it in.

**Comment by thebioengineer** [comment]
I think we added a general git ignore for PDF's. you can add a .gitignore file to the coxph verification folder and add a specific "do not ignore" line:

```

## keep the verification report pdf output
!verification_report.pdf

```

**Review by thebioengineer — APPROVED** [review]
just push the updated date for the PDF and you are good.

**Pull request merged**
