### PR TITLE
Adding Commit Hash into report

### PR DESCRIPTION
**Pull request by thebioengineer**
Capturing commit hash, and hashsums of input data in report.

Work in progress.

### CODE REVIEW

**Comment by benkeser** [comment]
Any way to make this generalize to builds that occur off of travis?

E.g., check for existence of a `TRAVIS` environment variable and if not there use `git` CLI commands to retrieve commit?

**Comment by thebioengineer** [comment]
yes, I was mainly seeing how this would work. I will add ability to get current hash via cli.

**Review by nhejazi — APPROVED** [review]
This looks great, thanks for the work on this @thebioengineer! I made some minor tweaks in 386e7c1, which moves the `hash_algorithm` choice to `_common.R`, touches up formatting, and adds a link to view the diff of the commit whose hash is recorded.

**Comment by benkeser** [comment]
@thebioengineer @nhejazi 

Not sure what happened with this PR, but lots of files changed now. Possible to merge with current `master` and fix conflicts?

**Comment by thebioengineer** [comment]
@benkeser - Not sure what happened - I had branched off of master when I made it 🤷 merged in the latest master.

@nhejazi - interesting idea! I like being able to see the expected diffs in the commits.

**Pull request merged**
