### PR TITLE
consolidating "data-level" parameters into `_common.R`

### PR DESCRIPTION
**Pull request by nhejazi**
The purpose of this PR is to migrate any "data-level" parameters (e.g., LLOD/LLOQ definitions) into the top-level `_common.R` script shared across individual analyses. Such values will be removed from any of the `*/code/params.R` files that are meant to control the "analysis-level" parameters.

### CODE REVIEW

**Comment by benkeser** [comment]
@nhejazi Why are so many files shown as changed in this PR?

**Comment by nhejazi** [comment]
A lot of the changes marked in the diffs look redundant with those that have recently been merged into master — could you try pulling from master into this PR, I’d expect the number of changes to be much fewer once the two are re-synced.

**Comment by benkeser** [comment]
It is up to date with `master`.

**Comment by benkeser** [comment]
Well I was going to request a review, but that appears difficult given it's hard to tell what files have actually changed here.

If this build completes, I'm going to merge and will followup with @KenLi93 and @cyu-hvtn about where I've touched their code.

I'll open a separate PR for some of the other minor issues raised.

**Comment by benkeser** [comment]
Going to go ahead and merge.

@KenLi93 and @cyu-hvtn please see changes to your `params` files in this PR. I have removed as much redundancy as possible between `_common.R` and directory-specific `params`.

**Pull request merged**
