### PR TITLE
Working PR for ENSEMBLE CoR report

### PR DESCRIPTION
**Pull request by benkeser**
@youyifong @yiwenlu, please submit ENSEMBLE-related CoR code to this branch (`ensemble_cor_report`). Will merge to `master` once there is a stable build on travis with mock data.

### CODE REVIEW

**Comment by benkeser** [comment]
Current build [breaks in `cor_coxph`](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/526883141#L5493) with error:

````
Error in solve.default(g$var, coef(g)) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0
Calls: source ... svycoxph.survey.design -> solve -> solve -> solve.default
Execution halted
````

**Comment by youyifong** [comment]
Hi David, I am not too sure I understand the version of code that is run in
this PR. Is it the same code as current master branch?
Thanks,
Youyi

**Comment by benkeser** [comment]
> Is it the same code as current master branch?

Now it is. I will just periodically merge with `master` to keep the PR as up to date as possible. You can still submit PRs and I will merge them here as a "holding place" until the code is stable, at which point I'll merge with master.

**Comment by youyifong** [comment]
@benkeser I think I got the picture. It seems two reports are still failing, one in cor_graphical for moderna (https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/526992538) and one in cor_coxph for ensemble (https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/526992542). Am I reading this right?

**Comment by youyifong** [comment]
I find that I am able to run cor_coxph for ensemble mock locally using code from the master branch.

**Comment by benkeser** [comment]
This still [breaks in `cor_coxph`](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/527514441#L4601), even with most recent code from `master` merged

````
Error in solve.default(g$var, coef(g)) : 
  Lapack routine dgesv: system is exactly singular: U[1,1] = 0
Calls: source ... svycoxph.survey.design -> solve -> solve -> solve.default
Execution halted
Makefile:10: recipe for target 'cor_coxph' failed
````

**Comment by youyifong** [comment]
I see what I did wrong. Just submitted a PR. Thanks.

**Comment by benkeser** [comment]
@youyifong, your `Region` fix (ff296f9) will now build on this PR.

**Comment by youyifong** [comment]
Got it.

**Comment by youyifong** [comment]
I think this is because the risk score is a constant for everyone:
> summary(dat.vac.seroneg$risk_score)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  -6.91   -6.91   -6.91   -6.91   -6.91   -6.91

**Comment by benkeser** [comment]
Interesting. @brborate, have you seen this behavior as well? I guess the most likely case is that the super learner is returning the simple mean model. Obviously this doesn't seem to happen on the real data, correct?

@youyifong, you've run this code on the real data, correct? If we get a stable build on the real data, then I'm ok merging this branch with `master`. In the meantime, we could check with Peter that there are indeed predictive variables in the simulated data.

**Comment by youyifong** [comment]
I just re-ran it on cosrv using real ensemble data and the latest risk
score code and it worked.

**Comment by brborate** [comment]
> Interesting. @brborate, have you seen this behavior as well? I guess the most likely case is that the super learner is returning the simple mean model. Obviously this doesn't seem to happen on the real data, correct?
> 
> @youyifong, you've run this code on the real data, correct? If we get a stable build on the real data, then I'm ok merging this branch with `master`. In the meantime, we could check with Peter that there are indeed predictive variables in the simulated data.

This shouldn't happen with real data sure. Even with mock data, I am seeing this for the first time; we have had predicted variables in the mock data until now as well. 👍

**Comment by youyifong** [comment]
To clarify, using the mock ensemble data,

For the full data, we have some variability

> summary(dat.mock$risk_score)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 -6.907  -6.907  -6.907  -6.219  -6.907  -0.858

For baseline neg vaccine arm, we have no variability

> summary(dat.vac.seroneg$risk_score)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  -6.91   -6.91   -6.91   -6.91   -6.91   -6.91

**Comment by benkeser** [comment]
@brborate, still seeing some errors from the risk report build with the new mock data. Any ideas?

**Comment by brborate** [comment]
Checking now.

**Comment by brborate** [comment]
@benkeser I think I have to push to (ensemble_cor_report) branch as well to make this work in sync. Configuring this at my end now. 👍

**Comment by benkeser** [comment]
@yiwenlu Currently [this PR breaks](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/532406227#L4769) in `cor_graphical` pre-processing. Could you look into this?

**Comment by brborate** [comment]
@benkeser I am also finding that Travis encounters lots of tex errors while making the risk score report. I think this needs to be fixed as well, correct? I am trying to reproduce this at my end. Hope to replicate this issue and fix soon.

**Comment by yiwenlu** [comment]
> @yiwenlu Currently [this PR breaks](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/532406227#L4769) in `cor_graphical` pre-processing. Could you look into this?

@benkeser just submitted PR #534 to fix this

**Comment by benkeser** [comment]
[Current error](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/532895231#L4647)

Looking for intercurrent cases in ENSEMBLE and not finding

**Comment by youyifong** [comment]
I think the merged code should not have this error again. Will travis be
triggered to run by the merging?

**Comment by benkeser** [comment]
> Will travis be triggered to run by the merging?

Yes, it's currently running

**Comment by youyifong** [comment]
There is another issue related to the new cID50 table that would not run
for ensemble data. I just opened a new PR 537 for that.

**Comment by benkeser** [comment]
@youyifong, I worry that your changes to the config have now impacted the other code. The [current build](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/532941004#L4833) breaks now in `cor_graphical`. Could you please work with @cyu-hvtn and @yiwenlu to resolve changes that need to occur as a result of the new `config`?

**Comment by benkeser** [comment]
> @youyifong, I worry that your changes to the config have now impacted the other code. The [current build](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/532941004#L4833) breaks now in `cor_graphical`. Could you please work with @cyu-hvtn and @yiwenlu to resolve changes that need to occur as a result of the new `config`?

Please disregard. This is still breaking in `cor_coxph`. I misinterpreted the output.

**Comment by youyifong** [comment]
That is a relief.

The bug fix and the new changes happening at the same time complicates
things. Hopefully the latest commits get us closer to a stable state.

**Comment by youyifong** [comment]
I think changing the output folder locations in cor_coxph will impact other
modules. I will open a new PR to fix that soon.

**Comment by benkeser** [comment]
[Current error](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533030518#L4836)

**Comment by benkeser** [comment]
@youyifong, still having [problems finding directories](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533044775#L4837).

Perhaps you need a clean pull of the repo to test locally, as you may have created directories on your local machine that don't exist in the repo?

**Comment by benkeser** [comment]
@youyifong I think your piece succeeded for ensemble. Moderna still running. 

@yiwenlu [a bug](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533051576#L5407) now cropped up in cor_graphical

**Comment by youyifong** [comment]
That is a relief. Thanks. I will check in future changes to the main
branch.

**Comment by yiwenlu** [comment]
> @yiwenlu [a bug](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533051576#L5407) now cropped up in cor_graphical

@brianSimpkins I think Kendrick's CoR_assay_graphics.R broke for Janssen Pooled Correlates Report, could you take a look?

**Comment by benkeser** [comment]
@yiwenlu @brianSimpkins it seems this fixed problems for Moderna, but [problems persist for ENSEMBLE](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533117828#L5505)

**Comment by brianSimpkins** [comment]
> it seems this fixed problems for Moderna, but problems persist for ENSEMBLE

@yiwenlu the issue now seems to be stemming from "CoR_wrcdf_with_VE_lines.R". Is this one of your script files, or should I take a look?

**Comment by benkeser** [comment]
> now seems to be stemming from "CoR_wrcdf_with_VE_lines.R"

or is that @youyifong?

**Comment by yiwenlu** [comment]
> > it seems this fixed problems for Moderna, but problems persist for ENSEMBLE
> 
> @yiwenlu the issue now seems to be stemming from "CoR_wrcdf_with_VE_lines.R". Is this one of your script files, or should I take a look?

@brianSimpkins This is Kendrick's, could you take a look?

**Comment by brianSimpkins** [comment]
Sure, no problem.

**Comment by benkeser** [comment]
[Current error](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533459988#L4833)
@youyifong @brianSimpkins @yiwenlu

**Comment by youyifong** [comment]
It looks like the bug fixes I submitted got lost in Brian’s code. I will
submit a PR with combined fixes.

**Comment by youyifong** [comment]
Hi Brian, I looked at the changed files in your PR and wasn't able to tell
what was changed. It seems safer for you to add in the changes I made. If
you look at

https://github.com/CoVPN/correlates_reporting/pull/547/files

and search for

attr(config,"config")

you will see two lines. Those were the changes needed to avoid the current
error.

Thanks,
Youyi

attr(config,"config")

**Comment by brianSimpkins** [comment]
Hi Youyi, I'm sorry for the delay - it's been a hectic morning for me. Previously, the code was selecting primary endpoints using the original definition - 7 days post-day57 - before producing the wrcdf plots, one for each timepoint. To update for ENSEMBLE, I selected primary endpoints by checking for 7 days post-day29, and then only produced the day29 figures.

I am sorry that my code absorbed your changes. Maybe you can submit a new PR? Or I can make the changes locally and then submit my own PR? Up to you.

One more thing -
My original PR (based on the master branch) passed the new code. However, when the changes were rolled into ensemble_cor_report, the build failed. The issue now is that this files 'cor_coxph/output/D57/marginalized.risk.no.marker.MockCOVE.Rdata' and 'cor_coxph/output/D29/marginalized.risk.no.marker.MockENSEMBLE.Rdata' don't exist. Do you know what Kendrick was searching for? And if so, does it go by a different name now?

Thanks,
Brian

**Comment by yiwenlu** [comment]
Hi Brian,

I don't think Youyi know the details of Kendrick's output. I am thinking
maybe you could run the code locally by setting "Sys.setenv(TRIAL =
"moderna_mock")" at very beginning and check if it will generate
cor_coxph/output/D57/marginalized.risk.no.marker.MockCOVE.Rdata
successfully and debug from there?

And a quick question about your edit - is it generic for both Moderna and
Janssen studies, i.e., studies with and without Day 57 endpoints?

Best,
Yiwen

**Comment by yiwenlu** [comment]
Oops sorry, I didn't notice the path is from cor_coxph folder, so Youyi may
know what's happening here.

Best,
Yiwen

**Comment by youyifong** [comment]
Hi Brian and Yiwen,

The path issue is due to unfortunate timing in my making some changes to
make the code more general. The fix should be easy.

Brian, could you update the loading of marginalized.risk.no.marker using
the following as an example in CoR_wrcdf_with_VE_lines.R? I think there are
three places.

    load(paste0("../cor_coxph/output/",
attr(config,"config"),"/PrimaryD57/marginalized.risk.no.marker."%.%study_name%.%".Rdata"))

Thanks,
Youyi

**Comment by benkeser** [comment]
@yiwenlu @brianSimpkins @youyifong looks like the ensemble build succeeds through your code 🎊 

@Larsvanderlaan getting [an error](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533569072#L5507) in cor_threshold now

**Comment by youyifong** [comment]
Awesome. Thanks, Brian!

This could be where the error started in the cor_threshold analysis:

Warning messages:
55271: Project requested R version '4.1.0' but '4.0.4' is currently being used
55282: In max(data[data$EventIndPrimaryD57 == 1 & data$Trt == 1 &
data$Bserostatus ==  :
5529  no non-missing arguments to max; returning -Inf
5530Error in `[[<-.data.frame`(`*tmp*`, t %.% a, value = logical(0)) :
5531  replacement has 0 rows, data has 38615
5532Calls: [[<- -> [[<-.data.frame
5533Execution halted
5534Makefile:11: recipe for target 'data' failed
5535make[1]: *** [data] Error 1
5536

Rscript code/Run_Threshold_analysis.R

**Comment by Larsvanderlaan** [comment]
Bug was caused by me including Day57 markers for JJ analysis. Pull request #549 should fix

**Comment by benkeser** [comment]
@Larsvanderlaan still a bug
https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/533609832#L4946

**Comment by brianSimpkins** [comment]
Sorry for the delay, I started school this past week! I know what the problem is - as soon as I reach a computer I can fix it.

**Comment by youyifong** [comment]
@benkeser the debug messages I added to the likes of cor_tabular/report.rmd were not printed. So the errors probably happened sometime earlier

**Comment by benkeser** [comment]
@brborate, current [risk build errors](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/537318431#L1969)

looking for something called `Gain` -- can't find it.

**Comment by brborate** [comment]
@benkeser , looking into this and will push the fix in a bit.

**Comment by youyifong** [comment]
Thanks, David. By the way, I just sent some messages to the Teams chat. It
would be nice to have a chat platform that is convenient for you and Nima
as well. The github commenting works, but since we get notified by emails,
it seems a little less conducive.

[image: image.png]

**Comment by brborate** [comment]
PR #560 issued to fix this

**Comment by benkeser** [comment]
@brborate could you fix the merge conflict and resubmit? Note I had to move up your definition of `threshold` because it was not defined in the `COVE` code.

**Comment by brborate** [comment]
> @brborate could you fix the merge conflict and resubmit? Note I had to move up your definition of `threshold` because it was not defined in the `COVE` code.

Thanks David for pointing this. I wasn't able to replicate this before. Did a pull and fixed as update to same PR (#560) 👍

**Comment by benkeser** [comment]
FYI @youyifong @nhejazi, I just updated file paths again. I think the issue is that the `R` session in the parent report is run in the project root directory. So we need to make things appropriate to that.

Overall, we should consider simplifying the `here` architecture using the `here::i_am` approach rather than the `.here` file approach. I think this would simplify a lot of these annoying issues.

**Comment by benkeser** [comment]
@brianSimpkins @yiwenlu [current error](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/537405390#L5940) in `cor_graphical` -- can't find a file.

**Comment by benkeser** [comment]
> @brianSimpkins @yiwenlu [current error](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/537405390#L5940) in `cor_graphical` -- can't find a file.

aaf3284 contains what I think is the fix.

**Pull request merged**
