### PR TITLE
Working PR for Janssen immuno report builds

### PR DESCRIPTION
**Pull request by benkeser**
In order to keep a stable `master`, please submit PRs that extend code related to the Janssen analysis to the `ensemble_immuno` branch. 

@KenLi93 @cyu-hvtn @yiwenlu @dilu963 @youyifong @thebioengineer @nhejazi FYI

### CODE REVIEW

**Comment by benkeser** [comment]
@brianSimpkins, currently breaking due to trying to load common.R from wrong folder:

https://travis-ci.com/github/CoVPN/correlates_reporting/jobs/523358192#L2594

**Comment by brianSimpkins** [comment]
Ah, that's rather embarrassing - an artifact from running the script locally. I'll open a new PR that fixes this problem.

**Comment by benkeser** [comment]
@brianSimpkins, now [an error](https://travis-ci.com/github/CoVPN/correlates_reporting/jobs/523395714#L2157) looking for a file.

**Comment by benkeser** [comment]
Moderna code currently breaks https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/523459479#L2590

**Comment by youyifong** [comment]
This is where it breaks:

here() starts at /home/travis/build/CoVPN/correlates_reporting/immuno_graphical
2589[1] "Data preprocess"
2590Error in `[.data.frame`(dat, , c("Ptid", "Trt", "MinorityInd",
"HighRiskInd",  :
2591  undefined columns selected
2592Calls: %>% ... replicate -> sapply -> lapply -> FUN -> [ -> [.data.frame
2593

**Comment by benkeser** [comment]
The good news is that the Janssen report builds!

@brianSimpkins, could you take a look at the Moderna error when you have another minute?

**Comment by brianSimpkins** [comment]
I've opened a new PR that should fix it. Thank you all for bearing with me.

**Comment by benkeser** [comment]
@brianSimpkins, https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/523466847#L2125

**Comment by brianSimpkins** [comment]
Thanks David for the heads-up. The new form of the mock data introduced a bug. I've submitted a PR to fix it.

**Pull request merged**
