### PR TITLE
new tables, new config entries, new output file location

### PR DESCRIPTION
**Pull request by youyifong**

### CODE REVIEW

**Comment by benkeser** [comment]
Should this go to master or ensemble_cor?

**Comment by youyifong** [comment]
Master I think. Most is the commits are already on ensemble_cor, a few are
new ones, concerning the refactoring.

Are we going to do away with ensemble_cor at some point?

**Comment by youyifong** [comment]
we are getting this error. is it just a fluke? @brborate @benkeser 

Running 1_baselineRiskFactors variable set 
[1] 2
[1] 1
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated

**Comment by brborate** [comment]
Thanks @youyifong. There is a tex error I am seeing that occurs on Travis due to which I think the Moderna mock risk report is not compiling it seems. But I was not able to replicate the error at my end last week.  I will look at this tomorrow in detail.  @benkeser @youyifong  Am I reading the error correctly over here or am I missing anything?

**Comment by benkeser** [comment]
@brborate The error is due to the surrogates analysis taking too long.

I turned off the surrogates analysis on the `ensemble_cor_report` branch.

**Comment by youyifong** [comment]
@benkeser Could you take a look at the current hiccup? https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/534379749

**Pull request merged**
