### PR TITLE
update `renv.lock` with xgboost v1.1.1.1

### PR DESCRIPTION
**Pull request by brborate**

### CODE REVIEW

**Comment by brborate** [comment]
Done

**Comment by nhejazi** [comment]
@brborate The diff still indicates a change from R 4.0.4 to 4.0.2, perhaps you may have forgotten to push the most recent changes?

**Comment by brborate** [comment]
Yes, will be pushing changes tomorrow, and that will include all changes suggested by David.

**Comment by benkeser** [comment]
Is this good to merge?

**Comment by brborate** [comment]
I am passing the seed to the run_cv_sl_once function. Seems like the code is good to merge now.  👍

**Pull request merged**
