### PR TITLE
Surrogates 34varsets

### PR DESCRIPTION
**Pull request by brborate**
@benkeser   Code runs but takes a long time; so haven't been able to run all variable sets at my side. Travis might fail I think. If I set verbose = TRUE, code generates a lot of output which also might not work for Travis.

### CODE REVIEW

**Comment by benkeser** [comment]
Is this for ENSEMBLE or COVE or both?

**Comment by brborate** [comment]
Currently only for COVE.  Once this works at Moderna's side, I will update it for ENSEMBLE  👍

**Comment by benkeser** [comment]
Currently [it's breaking](https://travis-ci.com/github/CoVPN/correlates_reporting/jobs/526959878#L6641) because it can't find reticulate.

- Could you confirm that reticulate is included in the lock file?
- Is it possible to default to the simpler SL library (that in particular avoids calling python) for the travis builds on mock data?

I'm just trying to understand if we can maintain a stable build on travis or not given the length of run time involved here.

**Comment by brborate** [comment]
sounds well; will update and make these checks. In a call at the moment. Will do as soon as done. 👍

**Comment by benkeser** [comment]
Getting a [stalled out](https://app.travis-ci.com/github/CoVPN/correlates_reporting/jobs/527022693#L6663) build on travis. Maybe this is inevitable for this analysis?

**Comment by brborate** [comment]
I think so; I am thinking we should let Moderna run their data and see what we find.

**Comment by benkeser** [comment]
Ok thanks

**Comment by benkeser** [comment]
@brborate, I haven't been able to verify the code due to issues with AWS account. I'm going to go ahead and merge. We'll probably just need to schedule meeting/s with Weiping to de-bug anything that comes up manually. 

Going to go ahead and merge this PR to prepare for that.

**Comment by brborate** [comment]
@benkeser this sounds well.

**Pull request merged**
