### PR TITLE
update Rmd debug messages; modify index_cor so that cor_tabular is always chapter 1

### PR DESCRIPTION
**Pull request by youyifong**

### CODE REVIEW

**Comment by youyifong** [comment]
@benkeser  Do you see any problems with the changes I made in index_cor? It seems nice to always have cor_tabular to be chapter 1, so I changed ## in the preamble to textbf.

**Comment by youyifong** [comment]
@benkeser  I put Disclaimers chapter back so that we can be consistent with the real moderna report. I just added some text that would work for all trials.

**Comment by benkeser** [comment]
That should be fine. But I think we need to work with @cyu-hvtn, who, if I remember correctly, had to manually number tables in her section. Not sure whether/how this will play nicely with the code you added for table/figure counting.

**Comment by cyu-hvtn** [comment]
The numbering should be fine. The tables are numbered automatically

**Pull request merged**
