### PR TITLE
Working PR for integrating Janssen risk score report

### PR DESCRIPTION
**Pull request by benkeser**
@brborate, this branch "turns on" automated building of the risk report for Janssen. Please submit PRs to merge into this branch. We'll merge into `master` once we have a stable build here.

### CODE REVIEW

**Comment by benkeser** [comment]
The build currently times out due to a lack of output. @brborate, should we go ahead and merge anyway? Or would you like to try to get a stable test build?

**Comment by brborate** [comment]
> The build currently times out due to a lack of output. @brborate, should we go ahead and merge anyway? Or would you like to try to get a stable test build?

@benkeser I checked my code and ran it with moderna and janssen mock data, and it runs fine and generates output within around 4 minutes.  I also see that print outputs given by travis are different than when I run the code on rhino. For example, travis run printed output is:  

**Warning message:
Project requested R version '4.1.0' but '4.0.4' is currently being used 
[1] "PacIsl dropped from risk score analysis as it had fewer than 110 1's or 0's."
[1] "Make sure data is clean before conducting imputations!"
[1] "No missing values to impute in any risk variables!"**

But print output from my code is:

**Package created on 2021-07-13
[conflicted] Will prefer dplyr::filter over any other package
[conflicted] Will prefer dplyr::summarise over any other package
[1] "NatAmer dropped from risk score analysis as it had fewer than 112 1's or 0's."
[1] "PacIsl dropped from risk score analysis as it had fewer than 112 1's or 0's."
[1] "WARNING: URMforsubcohortsampling variable has more than 5% values missing! This variable will be dropped from SuperLearner analysis."
[1] "Make sure data is clean before conducting imputations!"
[1] "Imputing missing values in following variables:  HIVinfection"
[1] "HIVinfection"**

Am really not sure why the printed output should be different. Could it be the R.version used by travis when it runs code? I see it is 4.0.4  instead of 4.1.0.

**Comment by brborate** [comment]
I am thinking we could merge it and see if Youyi can run at his end, and if it runs fine, then we should be good. Have done all checks from my side, and seems like the code is good.  👍

**Comment by benkeser** [comment]
@brborate, I am wondering whether you have pulled the most recent mock data? When I run locally, I see the same output as Travis.

**Comment by brborate** [comment]
Thanks @benkeser, I pulled the upstream master last night before running; but let me ensure it once again.

**Comment by benkeser** [comment]
I was able to successfully run the risk report locally. I just turned on `verbose` output to try to avoid the travis time out. Let's confirm it builds on travis and then will merge.

**Comment by brborate** [comment]
That is a good idea. Meanwhile am making inputFile for risk score at my end as well.

**Comment by brborate** [comment]
ok now, I am getting the same printed messages at my terminal as travis. Seems the code for creating data_processed has changed and I just had to make a new data_processed.csv.   Glad that I can reproduce the error.  Working at it.

**Comment by brborate** [comment]
ok, to confirm, Superlearner ran fine at my end. So it seems travis timing out may be the thing.

**Comment by benkeser** [comment]
Confirming stable build on travis now @brborate. Merging now.

**Pull request merged**
