### PR TITLE
Test new raw data

### PR DESCRIPTION
**Pull request by yiwenlu**
fix y range error in my cor_graphical codes @youyifong

### CODE REVIEW

**Comment by youyifong** [comment]
Yiwen, could you send me a copy of the file you changed by email? I am thinking that I can test it out locally and if it works, check it in for you as part of PR 255.

**Comment by benkeser** [comment]
Should this PR be closed? Have all relevant changes now been included in #255?

**Comment by youyifong** [comment]
Yiwen, your call.

David, please let me know when 255 is merged. I am ready to start a new PR
for minorityInd.

Thanks,
Youyi

**Comment by youyifong** [comment]
Works for me. Please go ahead closing #255.

Best,
Yiwen

**Pull request closed without merging**
