### PR TITLE
reporting adjustments and figure placement

### PR DESCRIPTION
**Pull request by nhejazi**
To address recent comments about reports, this PR
* adjusts how LaTeX float environments are handled to fix how immunogenicity and CoR graphics appear relative to report sections (incorrect before)
* updates the group authorship note to use the name "USG COVID-19 Response Biostatistics Team"

Additionally, the PR
* updates the shared `renv` library
* re-organizes how supplementary files are stored, introducing the new `css/` and `latex/` directories at the top level
* changes the use of `study.name` to `study_name` in the `cor_coxph` code so as to use the study name variable exported in `_common.R` (removing `study.name` from the `params.R` file of `cor_coxph`)

### CODE REVIEW

**Comment by youyifong** [comment]
Looks good to me.
Youyi

**Comment by nhejazi** [comment]
@benkeser [this build error](https://travis-ci.com/github/CoVPN/correlates_reporting/builds/221111033#L11626) is what I've been seeing on Travis consistently for the CoR Cox-PH analyses. The builds run fine for me locally, but use parallelization. Is there a way that we can further reduce the resource-burden of this set of analyses (assuming that's the issue)?

**Comment by youyifong** [comment]
B and numPerm are currently defined in coxph/code/params.R

B=1e3 # number of bootstrap replicates 1e3
numPerm=1e4 # number permutation replicates 1e4

We can also make them arguments to cor_coxph.R and supply that dynamically
in the scripts. Is there a way to tell that this is a travis build
programmatically?

**Comment by nhejazi** [comment]
Thanks, @youyifong --- I should have noted that I manually set these to very low numbers when I build the report manually; however, this is already automatically handled in the Travis configuration file, via https://github.com/CoVPN/correlates_reporting/blob/cor_report_fixes/.travis.yml#L46-L48. For those limited bootstrap and permutation numbers, I'd expect the Cox-PH analysis to build quickly even on a single core. Is there another element of the analysis that might be time/resource-intensive?

**Comment by youyifong** [comment]
It is nice to have the downsizing integrated. Could it be that the immuno
report has grown? Travis seems to enforce a 10 min limit. Is that new?

No output has been received in the last 10m0s, this potentially
indicates a stalled build or something wrong with the build itself.
11627

**Comment by benkeser** [comment]
> Travis seems to enforce a 10 min limit. Is that new?

That's always been the case. We've had, at times, to request that code print messages providing status updates so that the builds continue.

I think we need to go back to the travis build logs and git diffs to see what changes may have caused this.

**Comment by benkeser** [comment]
What's the status of this PR @nhejazi ?

Is it ready to be merged in spite of the Travis time out error?

**Comment by nhejazi** [comment]
The formatting fixes are good to go, but I'm hesitant to merge the PR without first fixing the Travis stalling issue. It's not clear to me why the timeout is happening, but if it results in breaking our automated reporting infrastructure, then it's not yet ready to merge imo. As a possible secondary check, I'm considering adding automated builds via GitHub Actions, which could serve as a way to build/serve the reports while avoiding any Travis-specific issues.

**Pull request merged**
