### PR TITLE
fix NA in violinplots and modify y-axis ranges

### PR DESCRIPTION
**Pull request by yiwenlu**

### CODE REVIEW

**Comment by benkeser** [comment]
@yiwenlu , could you merge this branch with `master` and push up to this `PR` to confirm it builds?

**Comment by yiwenlu** [comment]
@benkeser How to push up to this PR since it has been open? Can I close this one and make a new PR instead?

**Comment by benkeser** [comment]
If you push to the branch that is submitted for PR, it will automatically update the PR
________________________________

**Comment by yiwenlu** [comment]
@benkeser I just re-forked (guess I can pull and keep my fork up to date next time), made changes and submitted a new PR. Hopefully this also works.

**Comment by benkeser** [comment]
Closing since pre-empted by #116

**Pull request closed without merging**
