### PR TITLE
Stress testing the code

### PR DESCRIPTION
**Pull request by benkeser**
This branch attempts to generalize the reporting such that `assays` and `times` can be freely substituted in `_common.R` and appropriate output will be generated according to those options.

### CODE REVIEW

**Comment by benkeser** [comment]
@KenLi93 @cyu-hvtn I made a few tweaks to your code/reports to get things to build when fewer than 4 assays are requested. This makes this a bit more generalizable and modular. Please review the changes and, when this gets merged, be sure to pull into your local branches.

@nhejazi At this point I have confirmed that `immuno_report` builds with only binding antibodies assays (presumably any subset of assays, but only explicitly tested one combo). `cor_report` does not, but we can tackle that in another PR.

**Review by cyu-hvtn — APPROVED** [review]

**Comment by nhejazi** [comment]
Alright, sounds good by me @benkeser. I’ll take a look through this tomorrow and we can merge as soon as that review is complete. Agree with addressing the necessary changes for the CoR report separately (and keeping track in #196)

**Review by KenLi93 — APPROVED** [review]

**Comment by KenLi93** [comment]
Thank you for the updates, David! The changes look good to me

**Review by nhejazi — APPROVED** [review]
LGTM!

**Pull request merged**
