### PR TITLE
several updates in data processing and cor_coxph relates to D29 not being available

### PR DESCRIPTION
**Pull request by youyifong**
I am not sure what I needed to do, but somehow these commits seemed to remain on my fork when 197 was merged into upstream master

### CODE REVIEW

**Comment by benkeser** [comment]
> I am not sure what I needed to do, but somehow these commits seemed to remain on my fork when 197 was merged into upstream master

What commits specifically? I see no conflicts with `master` here.

**Comment by youyifong** [comment]
I don't think any of these changes is on Master. I thought they were part
of 197 and 197 was merged into master.

**Comment by benkeser** [comment]
> I don't think any of these changes is on Master. I thought they were part of 197 and 197 was merged into master.

I see what happened. We were going to merge #197 into #194, but decided to keep it separate because it looked like you were still adding. Then when #194 got merged to master, #197 got closed because I deleted the branch. Sorry about that. 

Whenever this PR is ready, ping me and I will merge.

**Comment by youyifong** [comment]
Yeah, it just keeps changing. I am going to make one more commit to 203 to
respond to Peter's comment #1 just now and will let you know.

**Comment by youyifong** [comment]
I was thinking of moving a line of code from cor_coxph to someplace
upstream so that Lars can use the same variables

t0=max(dat.vacc.pop[dat.vacc.pop[["EventIndPrimaryD"%.%pop]]==1,
"EventTimePrimaryD"%.%pop]); myprint(t0)

But because this depends on a couple of things, I had a change of mind. So
I am done with PR 203.

**Comment by benkeser** [comment]
Ok, will merge once build completes. 

You could compute `t0` as part of the data processing step and save in `data_clean`. Will let you figure out what's best with @Larsvanderlaan. Let me know what y'all decide because it is relevant for my cop analysis.

**Comment by youyifong** [comment]
That is a good idea. I just emailed Lars, so let's keep it this way for now
but revisit it later when the opportunity arises.

**Pull request merged**
