### PR TITLE
Changes to threshold plots

### PR DESCRIPTION
**Pull request by Larsvanderlaan**

### CODE REVIEW

**Comment by benkeser** [comment]
Hi @Larsvanderlaan, can you say a couple words about this PR. Does this need to be merged ahead of Moderna's real analysis (scheduled for today)?

**Comment by Larsvanderlaan** [comment]
Hi David, sorry about that.
This changed how the placebo risk displayed on the threshold plots is computed, and also increased the grid of thresholds plotted.

If possible, it would be ideal to merge this by Moderna's real analysis.

For whatever reason, some of Youyi's cor_coxph output is getting picked up in this pull request. Hopefully, this isn't an issue.

**Comment by benkeser** [comment]
Can you please merge with current `master` to see if that makes `cor_coxph` changes go away?

**Comment by Larsvanderlaan** [comment]
I just deleted his output locally and repushed. Seems to have fixed the issue.

**Pull request merged**
