### PR TITLE
add `study_label` to `config`

### PR DESCRIPTION
**Pull request by benkeser**

### CODE REVIEW

**Comment by youyifong** [comment]
Thanks, David. I was thinking about the following. Do you think it makes
sense?

moderna_real:
  <<: *default
  data_in_file: real_moderna_data.csv # Weiping can set
  data_name: real_moderna_data_processed.csv
  study_name: COVE
  study_label: COVE

moderna_mock:
  <<: *default
  data_in_file: COVID_VEtrial_practicedata_primarystage1.csv
  data_name: mock_moderna_data_processed.csv
  study_name: COVE
  study_label: Mock COVE

**Comment by benkeser** [comment]
> I was thinking about the following

Is 9603844 what you had in mind?

**Comment by youyifong** [comment]
Looks great. Thanks!
Youyi

**Comment by youyifong** [comment]
Hi David, I am sorry, but reading the code, I am just reminded that
study_name is used as part of the file names for some intermediate results.
Thus, it would be better to have study_name include "mock" so that the
intermediate results for mock can be saved side-by-side with the
intermediate results for real and no confusion will happen.

Would you mind changing it back to the way you had it, but with space
replaced by _, e.g

moderna_real:
<<: *default
data_in_file: real_moderna_data.csv # Weiping can set
data_name: real_moderna_data_processed.csv
study_name: COVE
study_label: COVE
moderna_mock:
<<: *default
data_in_file: COVID_VEtrial_practicedata_primarystage1.csv
data_name: mock_moderna_data_processed.csv
study_name: Mock_COVE
study_label: COVE

The other thing that bugs me a little is the variable name "study_label",
very hard to remember. Are COVE and ENSEMBLE terms for the clinical trials?
Would trial_name make more sense as the variable name?

By the way, sorry if you are getting this mail in multiple accounts. I
added your Emory email to the recipients list, but that may be redundant.

Thanks!
Youyi

**Comment by youyifong** [comment]
Or maybe we can call the variable study_name_code, a bit long, but at least
the name explicitly suggests that this variable is used for coding.

**Comment by youyifong** [comment]
underscore in study_name causes a problem in latex rendering. Having space
in file names does not seem to cause actual problems. If we are worried
about space in file names, maybe remove the underscore, e.g.

moderna_real:
<<: *default
data_in_file: real_moderna_data.csv # Weiping can set
data_name: real_moderna_data_processed.csv
study_name: COVE
study_name_code: COVE
moderna_mock:
<<: *default
data_in_file: COVID_VEtrial_practicedata_primarystage1.csv
data_name: mock_moderna_data_processed.csv
study_name: Mock COVE or MockCOVE
study_name_code: COVE

**Comment by youyifong** [comment]
See PR 349

**Pull request merged**
