### PR TITLE
Renaming weighting variables

### PR DESCRIPTION
**Pull request by nhejazi**
This PR addresses #315 by renaming weights and two-phase sampling indicators throughout all relevant analysis-specific code.

### CODE REVIEW

**Comment by nhejazi** [comment]
@youyifong This PR addresses the requested change in names of sampling indicators and weights. There was some need to interpret exactly how the weighting variables were used since different parts of the codebase follow different strategies for re-assigning the existing variables. Even if the automated checks pass, it'll be important for all contributors to carefully go through their updated code to make sure the changes to variable names do not cause downstream issues.

**Review by benkeser — APPROVED** [review]
Looks good as far as I can tell.

**Comment by thebioengineer** [comment]
Looks like my updates are getting deleted in this update - I will branch and request a merge into this PR.

**Comment by benkeser** [comment]
> Looks like my updates are getting deleted in this update. It might make sense for me to wait for this to be done, then add my changes after the fact.

I should've merged your PR first. Sorry about that.

**Comment by benkeser** [comment]
> > Looks like my updates are getting deleted in this update. It might make sense for me to wait for this to be done, then add my changes after the fact.
> 
> I should've merged your PR first. Sorry about that.

I think if we just merge master into this branch it should work?

**Comment by thebioengineer** [comment]
> > > Looks like my updates are getting deleted in this update. It might make sense for me to wait for this to be done, then add my changes after the fact.
 > > 
 > > 
 > > I should've merged your PR first. Sorry about that.
 
 > I think if we just merge master into this branch it should work?

It looks like you did? (23046d8) Not a big deal to me, but for verification I will need @youyifong to provide the rerun data_clean output using this new naming format.

**Comment by youyifong** [comment]
What do I need to do? 318 is not in the upstream master yet, right?

**Comment by benkeser** [comment]
@nhejazi @thebioengineer @youyifong 

Need help thinking through at what point this PR should be merged given other PRs are coming in fast.

**Comment by thebioengineer** [comment]
#315 (and this PR) might be better addressed asking folks to update independently given how quickly things update. or just ask all dev to pause, quickly merge everything into this, and people to check out accordingly

**Comment by benkeser** [comment]
Thanks. Maybe after merging #320 and #321 would be a good time for a brief pause?

**Comment by youyifong** [comment]
Sure. I have accumulated some changes on my fork, which I have not created
a PR for. I can wait till 318 is merged in and then resolve any conflict
there may be and then create a PR.

**Comment by benkeser** [comment]
OK I will merge those two PRs ASAP and then we can fix merge conflicts here in this PR and merge.

**Comment by nhejazi** [comment]
I would merge this ASAP and ask all existing / incoming PRs to fix issues introduced on their ends. This PR includes a lot of changes so the longer we wait, the greater the number of conflicts that will arise.

**Comment by nhejazi** [comment]
The advantage of merging this PR ASAP is that existing PRs that don’t play well with these changes will break (temporarily, at least flagging serious merge conflicts).

**Comment by benkeser** [comment]
Getting immuno report changes merged is priority number 1 given timeline. So I'm in favor of getting those fixes merged in ASAP and then merging this one after.

**Comment by benkeser** [comment]
> The advantage of merging this PR ASAP is that existing PRs that don’t play well with these changes will break (temporarily, at least flagging serious merge conflicts).

Agreed, but those PRs are more important to get merged in quickly than this one. 

Since I was slow in pulling the trigger, I will handle the merge conflicts. I'm going to go ahead and merge #320 and #321 now and then will start fixing conflicts on this PR.

**Comment by nhejazi** [comment]
Alright, that all sounds fine. The newest conflicts don’t look like too much of a pain to handle. The main thing is to merge this PR prior to work on any new PRs starting up (not including #320 and #321, of course) — we’d just want to avoid introducing further conflicts.

**Comment by benkeser** [comment]
@cyu-hvtn @KenLi93 @thebioengineer @youyifong @dilu963 @yiwenlu 

PLEASE PAUSE UPDATES UNTIL PR #318 IS MERGED. I WILL EMAIL WHEN MERGED.

**Comment by benkeser** [comment]
bd3a326 fixes the merge conflicts with #320 and #321. I will merge as soon as we get a successful build.

**Comment by youyifong** [comment]
Thanks!

**Comment by youyifong** [comment]
Hi David, could you merge 323 and 324 from Lars and me into upstream
master? This would allow us to see if the new llods etc take effect.
Thanks,
Youyi

**Pull request merged**
