### PR TITLE
fix bugs

### PR DESCRIPTION
**Pull request by yiwenlu**

### CODE REVIEW

**Comment by youyifong** [comment]
@benkeser Yiwen is working on a new update this afternoon that goes with this PR.

**Comment by benkeser** [comment]
@yiwenlu, will this fix the Moderna bug that we saw? I.e., can we ask Weiping to re-run?

**Comment by youyifong** [comment]
Can we wait a little while for @yiwenlu to submit a new PR? @benkeser

**Comment by benkeser** [comment]
Yes, sorry I saw your note right after I merged this PR.

**Pull request merged**
