### PR TITLE
Riskscore update for COVE

### PR DESCRIPTION
**Pull request by brborate**

### CODE REVIEW

**Comment by youyifong** [comment]
@benkeser @brborate I don't understand the error messages, which are somehow about git.

**Comment by benkeser** [comment]
What errors?

**Comment by brborate** [comment]
I think the errors are showing because we didn't give enough time for Travis to run all reports before merging into master.

**Comment by benkeser** [comment]
Ah I see. Yes, Bhavesh is correct. I'm just letting the build run on `master` instead of in the PRs

**Pull request merged**
