### PR TITLE
Changes related to the use of Perprotocol in data processing; switch ordering of censoring and computing fold changes of markers

### PR DESCRIPTION
**Pull request by youyifong**

### CODE REVIEW

**Comment by youyifong** [comment]
Error msg: ! I can't find file `_report_riskscore/covpn_correlates_riskscore.tex'.

**Comment by benkeser** [comment]
Fails in `cor_tabular/code/make_table_all.R` with error

```r
Error in eval(e, x, parent.frame()) : object 'corrset2' not found
```

@cyu-hvtn

**Comment by youyifong** [comment]
weird error: Error in `[.data.frame`(dat, , c("Ptid", "Trt", "MinorityInd", "HighRiskInd",  : 
  undefined columns selected
Calls: %>% ... replicate -> sapply -> lapply -> FUN -> [ -> [.data.frame
Execution

**Comment by youyifong** [comment]
But I was able to run 

Rscript code/descriptive_graphics_data_preprocess.R

on my linux machine.

**Pull request merged**
