### PR TITLE
Header and footnotes update

### PR DESCRIPTION
**Pull request by cyu-hvtn**

### CODE REVIEW

**Comment by cyu-hvtn** [comment]
Sorry didn't notice there were conflicts. I'll fix it.

**Comment by benkeser** [comment]
A lot of merge conflict resolutions in fa4844d9248125a3d046585f91df3f9430af3f0f are not correct. You have reverted many conflicts to the code on your branch that should’ve kept master code. Basically all of those conflicts should’ve kept the code on master.

**Comment by benkeser** [comment]
The only files that should be changed on master by this PR are files in the immuno_tabular folder. Right now it would update 26 files.

**Comment by benkeser** [comment]
Superseded by #206

**Pull request closed without merging**
