### PR TITLE
optimal surrogate

### PR DESCRIPTION
**Pull request by brborate**

### CODE REVIEW

**Comment by benkeser** [comment]
@thebioengineer, I'm verifying this analysis. Could I ask you to handle the PR?

**Comment by thebioengineer** [comment]
I can look at a high level, but I don't know superlearner and don't have much bandwidth this week. @nhejazi probably knows more - do you have the bandwidth?

**Comment by nhejazi** [comment]
I can put this on my to-do list but am running very low on bandwidth at the moment, so it may take me some time to be able to walk through the full implementation details.

**Comment by brborate** [comment]
Too early to say but I think i might have some bandwidth later in the week. If there's anything I could do to help here, please let me know. 👍

**Comment by benkeser** [comment]
I don't think it needs a super in depth review (that's what verification is for). Just high level comments on structure etc are OK

**Comment by benkeser** [comment]
Following up on this. @nhejazi @thebioengineer, can someone please handle this week?

**Comment by brborate** [comment]
Hi @benkeser, @nhejazi,  It seems we need to push the optimal surrogate analysis code so Weiping can run it on the real data soon. Is it possible for us to make checks and merge the code into main branch this week?  Please let me know if there's anything I could do to help here. 👍

**Pull request merged**
