### PR TITLE
immuno tables verification done

### PR DESCRIPTION
**Pull request by yiwenlu**

### CODE REVIEW

**Review by thebioengineer — CHANGES_REQUESTED** [review]
Please correct the date in the verification_report.Rmd to update to the current date and recompile the Rmd please! once thats done :+1:

```r
date: "`r Sys.Date()`"
```

**Comment by benkeser** [comment]
Do I see some `.RData` files included in this PR? Is that intentional?

**Comment by yiwenlu** [comment]
@benkeser Yes, they are intentional. RData files are my double programming results for comparing with Chenchen's original results

**Review by thebioengineer — APPROVED** [review]
@yiwenlu - pending decision with .rda from @benkeser, code looks good.

**Comment by benkeser** [comment]
I'd prefer to leave rda's out. I assume that @yiwenlu is programatically checking for agreement herself? I see no need to store the R data objects if so.

**Comment by yiwenlu** [comment]
@thebioengineer Is it okay to delete rda files in the verification_input and verification output folders, from the prospective view of verification process? If so, I will only store my verification code here.

**Comment by thebioengineer** [comment]
Keep them locally, but for the repo lets remove them.

**Comment by benkeser** [comment]
Still some `.Rdata` files lingering

**Comment by yiwenlu** [comment]
@benkeser how about now? I think you referred to verification outputs for cor report which I haven't finished yet

**Comment by benkeser** [comment]
Thanks @yiwenlu. There's a merge conflict in `immuno_tabular/verification/table_specifications.md`. Could you please fix and then I'll merge. Thanks!!

**Pull request merged**
