### PR TITLE
update mock raw data from Peter, add AU to IU conversion in data processing, add delta for bindN

### PR DESCRIPTION
**Pull request by youyifong**
The AU to IU conversion may also affect llod etc. Will update that when we have the info. For now, all binding variables are scaled with the conversion factors after censoring with llod and lloq etc. But the llod and lloq themselves are not touched.

### CODE REVIEW

**Comment by youyifong** [comment]
The changes include updated raw data file, conversion from AU to IU. These changes also broke my cor_coxph code where I created trichotomized version because the distribution of pseudoneutid80 changed a lot. Not sure if a similar reason caused this break in cor_graphical.

**Comment by benkeser** [comment]
@youyifong Could you merge this with current `master` and push to trigger a new build?

**Comment by youyifong** [comment]
rebuilding ...

**Comment by benkeser** [comment]
Currently breaking because somewhere in `cor_coxph` it is trying to call `rmarkdown::render`, which I don't think should be happening. @youyifong any idea what's going on here?

**Comment by youyifong** [comment]
I removed report from all in the Makefile and committed.

**Comment by youyifong** [comment]
Thanks!

**Comment by youyifong** [comment]
Just a thought. Would it be worth thinking about optimizing plotting code
to speed things up to make testing more efficient? I look at
Yiwen's cor_graphics_violin_scatter.R and it is mostly ggplot code. So I
don't know if it is even possible.

**Pull request merged**
